### ISSUE TITLE
Create a theme at runtime

### ISSUE THREAD

**Issue by detygon** [innocenzi/tailwindcss-theming#26]
Hi, thanks for your work! Is it possible to create a theme at runtime ? For example, based on the user settings. Or what would be a recommended approach to do so ?

**Comment by innocenzi** [comment]
Hey! I never did something like that, but since this is using CSS variables, it shouldn't be too hard to implement. 

It should depend on your stack, and I can't tell you a recommended way of doing this, but what I can think of right now is to create a theme with no colors (or just defaults), colors of which you would take from your data source (database/user settings with colors) to generate CSS at render time? 

Something like:
- You have a "default" theme with all of your colors
- You have a "custom" theme which doesn't change anything
- You have a form that allows the user change the colors
- You save the colors in your database
- On subsequent requests, you add a `<style>` tag in your `<head>` dynamically with a generated CSS (mapping of `--css-variables` and user colors), so the colors don't flash

Maybe I'm overengineering, just my hot take. Depend on what user settings implementation you want too.

**Comment by detygon** [comment]
Ok great, my stack is Tailwind, Alpine, Livewire, Laravel. I looked at the docs but I don't understand how to update the css variable as you said. Can you please, provide a little code snippet when you're free. Thanks in advance

**Comment by innocenzi** [comment]
Sure, this is an interesting problem to solve. I don't promise anything, but I'll try to do something.

**Comment by detygon** [comment]
That would be great, it'll make this tool really powerful + really useful for me.

**Comment by innocenzi** [comment]
Hey again,

So I won't be able to make an example right now, but I'll tell you with more details how I would implement it. 

First, I assume that you want custom colors from your users and not a predefined set. But either way, the implementation should be pretty similar. 

I will also assume you have a page where there is a kind of form with which users can build their themes, and that this page returns a pair of colors and values to the back-end. 

By colors and value, I mean that if you have the following theme configured in your `theme.config.js`:

```js
const main = new Theme() //
    .addColors({
        brand: "orange",
        background: "#1c1e26",
        "on-background": "#e1e1e1"
    });
```

In your back-end you will deal with something like an associative array:

```php
$theme = [
    'brand' => '36,164,239',
    'background' => '247,250,252',
    'on-background' => '26,32,44'
]
``` 

Now, notice the format of the colors: they are `R,G,B` values, because that's what `tailwindcss-theming` outputs in the CSS in order to deal with opacity. But the conversion from `#hex` to `r,g,b` shouldn't be too hard, and you should do it before you send the values to your back-end. For information, `tailwindcss-theming` uses the package `@ctrl/tinycolor` to work with colors, so you can use that. You could also actually convert `#hex` to `r,g,b` in your back-end, but I think this is a task for the front. 

Now that you have this array of colors, which you should save in your user settings (I won't go in that, because this is specific to your appliation, but you can save them however you want), the only thing you need to do is generate a custom `<style>` in your front. 

What you could do is have a `_partial.theme` Blade component like the following:

```php
<style>
:root {
    @foreach ($theme as $color => $value)
	    {{ sprintf('--color-%s: %s;', $color, $value) }}
	@endforeach
}
</style>
```

You can call it like that in your main layout **inside the `<head></head>` tags**: 

```php
@includeWhen(isset($theme), 'partials._theme', $theme ?? [])
```

What this does it that it overrides the current CSS variables in the `:root` by the new ones dynamically fetched from your database that you put in a `<style></style>` tag. 

If you user choses, for instance, light colors instead of your default dark ones, you could have something like this gif:

![Result](https://i.imgur.com/DQNZPOh.gif)

--- 

The implementation is obviously super specific to your project, but that's the simplest approach I could think of. In a real project I wouldn't do it exactly like that, but I hope it gives you a clear idea of how you should do it for yours. 

I'll close the issue but feel free to comment again if you have troubles.

**Comment by detygon** [comment]
I really appreciate. I'll work on it and share my implementation if possible. Keep up the good work
