### ISSUE TITLE
Tailwind 2 compatibility?

### ISSUE THREAD

**Issue by john-griffin** [innocenzi/tailwindcss-theming#35]
First of all thanks for the amazing work on this plugin, it really came at the right time for our project!

I'm currently trying to upgrade from tailwind 1.9.6 tailwind 2.0.2. After completing the upgrade guide I noticed the themes were not loading correctly. Looking at the generated css it seems all the color class names are being suffixed with `-default` now. For example the color named `on-background` will generate `text-on-background-default`.

This issue is happening in `2.4.3` and `v3.0.0-beta.2`.

Any ideas on how we complete the upgrade?

**Comment by innocenzi** [comment]
Hello,

The issue comes from this file: https://github.com/innocenzi/tailwindcss-theming/blob/9c370eeb1076bb48df86d127118df0670430bf8a/src/util/flattenColorObject.ts#L21 

Since Tailwind 2, the `default` key should be uppercased to `DEFAULT`.

Unfortunately I didn't have time to work on this plugin since a few weeks because of my work, and even though I still plan on upgrading it, it won't be before at least mid-january.

If you can confirm that this is the only issue with Tailwind 2, I can release an update quick enough though.

**Comment by john-griffin** [comment]
Thanks for the details. Yes that appears to be the main blocker to upgrading right now. The classes are being generated as expected, just with the wrong names.

**Comment by innocenzi** [comment]
Hey, I tagged a new beta version which should bring Tailwind 2 compatibility. Can you let me know if it works for you?

**Comment by john-griffin** [comment]
Thanks for the update - classes are now being generated as expected!

Unfortunately it appears that PurgeCSS is not working as expected with tailwindcss-theming. Using default Tailwind 2 purge config all themes are getting stripped out. Any ideas on that one?

**Comment by innocenzi** [comment]
Can you share your config? The plugin really just edits your `color` configuration and doesn't do more magic than that, so I'm not sure what would be the issue. 

Make sure you have followed the whole documentation on purge: https://tailwindcss.com/docs/optimizing-for-production

**Comment by john-griffin** [comment]
Yeah good point - I had an issue in the purge config. Looks good now!
